### ISSUE TITLE
The notebook `compare_git_branch_results.ipynb` in the test folder returns Type Error

### ISSUE THREAD

**Issue by yijianzeng** [EcoExtreML/STEMMUS_SCOPE#179]
@BSchilperoort Hi Bart, there are two points i encountered:
1.  `Before continuing, run the following command to ensure that you can change between the two branches without any errors:
!cd $path_to_repository; git checkout $main_branch; git pull
!cd $path_to_repository; git checkout $test_branch; git pull
M	config_file_crib.txt
Already on 'main'
Your branch is up to date with 'origin/main'.
Enter passphrase for key '/home/jovyan/.ssh/id_ed25519': `

Then it stuck since there is no prompt to enter the passphrase.

2. `---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [2], line 15
     12 else:
     13     raise ValueError("Unknown runner")
---> 15 config_path = model.setup(
     16     Location=model_location,
     17     StartTime=model_start,
     18     EndTime=model_end,
     19 )
     20 print("Path to config: " + config_path)

TypeError: setup() got an unexpected keyword argument 'Location'`

**Comment by BSchilperoort** [comment]
Hi Yijian, since the repositories are public now, it's probably easiest to clone the repo using `https://github.com/EcoExtreML/STEMMUS_SCOPE.git`, this should not require a login at all.

For the 2nd error: you are probably using an old version of PyStemmusScope. If you update that (`pip install --upgrade PyStemmusScope`) the notebook should run fine.
