### ISSUE TITLE
Importing soil thickness and root zone depth from outside the code

### ISSUE THREAD

**Issue by MostafaGomaa93** [EcoExtreML/STEMMUS_SCOPE#237]
Currently, the soil total thickness is fixed to 5 m in the `getModelSettings` ([here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/2f9f468186c5a115e272f0de10344e23104e9b2e/src/%2Bio/getModelSettings.m#L54)). Same also for the depth of the root zone is fixed to 3.5 m ([here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/2f9f468186c5a115e272f0de10344e23104e9b2e/src/%2Bio/getModelSettings.m#L5)). I believed that these two values can be changed from one site to another and also with different landcover, so in my opinion, it would be more convenient for the user if we can change these two values outside the code (through one of the input files).

**Suggestion solution**
We can add these two to the sheet `input.xlsx` and the user can change them from that sheet. Then, the value will be updated in the code ([here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/2f9f468186c5a115e272f0de10344e23104e9b2e/src/STEMMUS_SCOPE.m#L82-L83))

What do you think @yijianzeng and @bobzsu? If agreed, I am willing to do this adjustment and update the code with @SarahAlidoost

**Comment by SarahAlidoost** [comment]
@MostafaGomaa93 please consider adding those variables to the config file, see [onfig_file_template.txt](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/config_file_template.txt) instead of `input.xlsx`. The format `xlsx` is proprietary and it is not recommended according to FAIR data principles. 
Also, using `config_file_template.txt`, makes it easier to set up parameters using python interface in pystemmusscope.

**Comment by MostafaGomaa93** [comment]
@SarahAlidoost Is there another option than the config_file? just thinking because the config file is all about the path to the data folders, and no parameters are assigned there.

**Comment by SarahAlidoost** [comment]
> @SarahAlidoost Is there another option than the config_file? just thinking because the config file is all about the path to the data folders, and no variables are assigned in it.

Currently variables like “Location”, “startTime” and “endTime” are also in the config_file_template. The idea of having one configuration file is to follow community standards for coupling models: a config file should be used to `setup` a model (see [PyMT definition](https://pymt.readthedocs.io/en/latest/glossary.html#term-configuration-file)) or `initialize` a model (see [BMI definition](https://bmi.readthedocs.io/en/stable/glossary.html#term-configuration-file)). `model.setup` usually creates a working directory and finds the data based on the information in the config file. 

For stemmus_scope, it would be great to merge all configurations (IO directories) and tunable parameters (`getModelSettings` and `input.xlsx`, hardcoded values) into one file. This way, users are able to reproduce/reuse a workflow by changing one file instead of several files. In addition, having one file makes the development and maintenance easier. 

I agree that it is better to separate directories from parameters, like by creating sections in a [yaml file](https://en.wikipedia.org/wiki/YAML). However, it requires changing the format of `txt` to `yaml` and updating the reading and writing functions in stemmus_scope and pystemmusscope. For more info, see [an example of yaml file](https://github.com/EcoExtreML/zampy/blob/main/example_recipe.yml) to run zampy.

**Comment by MostafaGomaa93** [comment]
Thanks for the explanation @SarahAlidoost. I indeed agree with you. In the meantime, can we do it through the BMI? if agreed, I can add these two variables to the BMI table ([here](https://github.com/EcoExtreML/STEMMUS_SCOPE/issues/209)). I will also make a very slight change in the source code.

I already discussed the idea with @yijianzeng and he agreed.

**Comment by SarahAlidoost** [comment]
> Thanks for the explanation @SarahAlidoost. I indeed agree with you about having one file for all settings and parameters. In the meantime, can we do it through the BMI? if agreed, I can add these two variables to the BMI table ([here](https://github.com/EcoExtreML/STEMMUS_SCOPE/issues/209)). I will also make a very slight change in the source code.
> 
> I already discussed the idea with @yijianzeng and he agreed.

yes, it can be added to the BMI implementation. But the initial values of these two variables should be defined somewhere in the stemmus_scope code.

**Comment by MostafaGomaa93** [comment]
> > Thanks for the explanation @SarahAlidoost. I indeed agree with you about having one file for all settings and parameters. In the meantime, can we do it through the BMI? if agreed, I can add these two variables to the BMI table ([here](https://github.com/EcoExtreML/STEMMUS_SCOPE/issues/209)). I will also make a very slight change in the source code.
> > I already discussed the idea with @yijianzeng and he agreed.
> 
> yes, it can be added to the BMI implementation. But the initial values of these two variables should be defined somewhere in the stemmus_scope code.

Yes, the defalut values are already there in the code.

**Comment by SarahAlidoost** [comment]
> > > Thanks for the explanation @SarahAlidoost. I indeed agree with you about having one file for all settings and parameters. In the meantime, can we do it through the BMI? if agreed, I can add these two variables to the BMI table ([here](https://github.com/EcoExtreML/STEMMUS_SCOPE/issues/209)). I will also make a very slight change in the source code.
> > > I already discussed the idea with @yijianzeng and he agreed.
> > 
> > 
> > yes, it can be added to the BMI implementation. But the initial values of these two variables should be defined somewhere in the stemmus_scope code.
> 
> Yes, the defalut values are already there in the code.

The variables added to the table [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/issues/209#issuecomment-2205833332) are in the structure `ModelSettings`. Currently, model settings are loaded in different scripts as `ModelSettings = io.getModelSettings();`, see [search results](https://github.com/search?q=repo%3AEcoExtreML%2FSTEMMUS_SCOPE+path%3A%2F%5Esrc%5C%2F%2F+getModelSettings%28%29&type=code&p=1). Therefore, it is not possible to update the variables of `ModelSettings` through BMI because calling `io.getModelSettings()` will reset the values again. We need a workaround for this. @BSchilperoort what do you think?

**Comment by MostafaGomaa93** [comment]
**Notice to be considered**

I have done several tests in changing the ([`getModelSettings.Tot_Depth`](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/2f9f468186c5a115e272f0de10344e23104e9b2e/src/%2Bio/getModelSettings.m#L54)). To avoid errors in the model run, the following need to be considered:
- Minimum value that can be assigned to the `getModelSettings.Tot_Depth` = 300 cm. This is because the structure of the [`Dtrmn_Z`](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/2f9f468186c5a115e272f0de10344e23104e9b2e/src/Dtrmn_Z.m) function. In the future releases, if we want to change the `getModelSettings.Tot_Depth` to be < 300, then the `Dtrmn_Z` will need to be adjusted.
- Maximum value that can be assigned to the `getModelSettings.Tot_Depth`  = 1400 cm. That is because the [`getModelSettings.NL`](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/2f9f468186c5a115e272f0de10344e23104e9b2e/src/%2Bio/getModelSettings.m#L64C3-L64C27) = 100. So, if we want to let  `getModelSettings.Tot_Depth`  > 1400 cm, the `getModelSettings.NL` will need to be > 100.
- The following is a description of a required change (already done). The indices of the first 4 layers (layers close to land surface) are from 51 to 54 (as long as the total soil thickness equals 5 m). However, if we change the total soil thickness (not 5 m), then the indices of the first 4 layers will not be from 51 to 54 anymore. So, a simple change in these 3 files ([one](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/f96ca1ca8176cab732b5ba440ec206a988aeca31/src/calc_sfactor.m#L2C5-L2C58), [two](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/f96ca1ca8176cab732b5ba440ec206a988aeca31/src/calc_rsoil.m#L5C4-L5C48), [three](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/f96ca1ca8176cab732b5ba440ec206a988aeca31/src/%2Bsoilmoisture/calculateBoundaryConditions.m#L75)) to get the proper indices of the first 4 layers.

**Comment by yijianzeng** [comment]
> Currently variables like “Location”, “startTime” and “endTime” are also in the config_file_template. The idea of having one configuration file is to follow community standards for coupling models: a config file should be used to `setup` a model (see [PyMT definition](https://pymt.readthedocs.io/en/latest/glossary.html#term-configuration-file)) or `initialize` a model (see [BMI definition](https://bmi.readthedocs.io/en/stable/glossary.html#term-configuration-file)). `model.setup` usually creates a working directory and finds the data based on the information in the config file.

We can enrich the Config file with categories, following community standards: 'Directory Info,' 'Namelist,' etc.

**Comment by yijianzeng** [comment]
> For stemmus_scope, it would be great to merge all configurations (IO directories) and tunable parameters (`getModelSettings` and `input.xlsx`, hardcoded values) into one file. This way, users are able to reproduce/reuse a workflow by changing one file instead of several files. In addition, having one file makes the development and maintenance easier.

Strongly agree!

**Comment by yijianzeng** [comment]
> * The following is a description of a required change (already done). The indices of the first 4 layers (layers close to land surface) are from 51 to 54 (as long as the total soil thickness equals 5 m). However, if we change the total soil thickness (not 5 m), then the indices of the first 4 layers will not be from 51 to 54 anymore. So, a simple change in these 3 files ([one](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/f96ca1ca8176cab732b5ba440ec206a988aeca31/src/calc_sfactor.m#L2C5-L2C58), [two](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/f96ca1ca8176cab732b5ba440ec206a988aeca31/src/calc_rsoil.m#L5C4-L5C48), [three](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/f96ca1ca8176cab732b5ba440ec206a988aeca31/src/%2Bsoilmoisture/calculateBoundaryConditions.m#L75)) to get the proper indices of the first 4 layers.

This is linked to [issues 241](https://github.com/EcoExtreML/STEMMUS_SCOPE/issues/241#issuecomment-2222699598)
