### ISSUE TITLE
Trap variable is not found with BMI

### ISSUE THREAD

**Issue by MostafaGomaa93** [EcoExtreML/STEMMUS_SCOPE#271]
I made a new branch with one small edit (adding the `Trap` variable to BMI list [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8d1636042f407c573775ae6f58368706f24b19ce/src/STEMMUS_SCOPE_exe.m#L32C1-L32C51)). I asked @Crystal-szj  to make a new executable file using the Surf machine, but when I tested the new exe in the BMI notebook. I received this error.

![BMI_error](https://github.com/user-attachments/assets/5c6fc4ca-2284-41ad-919c-fa1ce7365532)

The error says the `Trap` variable is not found, so this refers to the discussion that we had last time. We made a new exe but seems the code changes are not recognized in this new exe.

**Comment by BSchilperoort** [comment]
How are you running the model, I assume on your local machine with Docker? Because then you need to build a new container image with the MATLAB executable file.

**Comment by MostafaGomaa93** [comment]
> How are you running the model, I assume on your local machine with Docker? Because then you need to build a new container image with the MATLAB executable file.

I run it on the ITC server and not using Docker. Usually, I run on the same machine and always the new exe is okay when Sarah makes the new exe

**Comment by BSchilperoort** [comment]
The BmiVariable in PyStemmusScope needs the `all_timesteps=True` argument.

**Comment by MostafaGomaa93** [comment]
> The BmiVariable in PyStemmusScope needs the `all_timesteps=True` argument.

I am adding it already but still zero

        **BmiVariable(
        name="transpiration_total",
        dtype="float64",
        input=False,
        output=True,
        units="cm s-1",
        grid=0,
        keys=["Trap"],
        all_timesteps=True,
    ),**

**Comment by SarahAlidoost** [comment]
> > The BmiVariable in PyStemmusScope needs the `all_timesteps=True` argument.
> 
> I am adding it already but still zero
> 
> ```
>     BmiVariable(
>     name="transpiration_total",
>     dtype="float64",
>     input=False,
>     output=True,
>     units="cm s-1",
>     grid=0,
>     keys=["Trap"],
>     all_timesteps=True,
> ),
> ```

can you please commit your change and push it to `add_rainfall_to_bmi`?

**Comment by MostafaGomaa93** [comment]
> can you please commit your change and push it to `add_rainfall_to_bmi`?

Done

**Comment by SarahAlidoost** [comment]
> Thanks @SarahAlidoost. After your suggestion and with the new exe, the error is gone but the `Trap` value in BMI is always zero. I check the shape of the `Trap`. It is a matrix like (1, n_timesteps) which is filled in with the value per every time step and
> 
> at KT = 1 -> Trap = 0 at KT = 2 -> Trap = 0 0.007 at KT = 3 -> Trap = 0 0 0.008
> 

I just saw this. The size of the variable `Trap` changes while the model runs, which is not compatible with BMI. To fix this, `Trap` should either always have a size of 1 or match the size of all time steps. Having a size of 1 is preferred, like the variable `RWUg`. Right now, though, this isn’t happening because `Trap` size keeps changing. Here is a list of changes to fix the issue:

- remove [this line ](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/b9b4f8231955589d3394ec5148950467eeaa4ec3/src/%2Bsoilmoisture/calculateEvapotranspiration.m#L41) 
- replace `Trap` in [this line](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/b9b4f8231955589d3394ec5148950467eeaa4ec3/src/%2Bsoilmoisture/calculateEvapotranspiration.m#L1) with `Tp_t`
- add `Tp_t=0;` before [this if block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/b9b4f8231955589d3394ec5148950467eeaa4ec3/src/%2Bsoilmoisture/calculateEvapotranspiration.m#L22) to make sure that it has a default value. 
- rename `Tp_t` with a clear name
- replace `Trap(k)` in [this line](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/b9b4f8231955589d3394ec5148950467eeaa4ec3/src/%2Bio/output_data_binary.m#L13C155-L13C162) with `Trap` as it is now just one value. 
- remove `all_timesteps=True` from bmi variables.

**Comment by MostafaGomaa93** [comment]
Many thanks, @SarahAlidoost, I implement them in this [PR](https://github.com/EcoExtreML/STEMMUS_SCOPE/pull/273).

**Comment by MostafaGomaa93** [comment]
I also checked the new exe and it works okay. Now both `Evap` and `Trap` are 1 size array and give value in BMI
