### ISSUE TITLE
Refactor `h_sub`, move all `h_` functions

### ISSUE THREAD

**Issue by BSchilperoort** [EcoExtreML/STEMMUS_SCOPE#98]
In STEMMUS_SCOPE.m, all `h_` functions are called using the script `h_sub`:

https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/d2fe0a671ab26430f086e1c8ee8272f4db6fa060/src/STEMMUS_SCOPE.m#L728

However, for model maintainability we want to remove all use of globals and running scripts.

Additionally, as all `h_` functions seem to tackle one specific part of the model, these should be moved to a separate Matlab package, e.g., a folder called `+heat_flux` (assuming that is what these functions do).

<hr>

To do:
- [ ] Move all `h_` files to their own package, with an appropriate name
- [ ] Convert `h_sub` into a function. Use structures to reduce the amount of input and output variables.
- [ ] Add documentation to all functions
- [ ] Make the required changes in the main file.
- [ ] Create a pull request for the changes

**Comment by SarahAlidoost** [comment]
@yijianzeng For each function below, please add one line explanation and suggest a better name in this issue, thanks

- h_sub
- hPARM
- h_MAT
- h_EQ
- h_BC
- hh_Solve
- h_Bndry_Flux

**Comment by SarahAlidoost** [comment]
@yijianzeng While refactoring `h*_` functions, I found major issues, see below. Please help to address them:

1. in this [giant if block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L176-L309), there are many codes used to calculate variable `Trap(KT)`. However, at the bottom of the script, `Trap(KT)` is reset in the line [Trap(KT) = Tp_t(KT);](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L330C5-L330C13). Is this correct? if so, unused codes will be removed!
2. `Evap_Cal` is calculated only `if NBCh == 1 `, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/h_BC.m#L37). Otherwise, all of the output of  `Evap_Cal` i.e. `[Rn_SOIL, Evap, EVAP, Trap, r_a_SOIL, Resis_a, Srt]` will be empty. `[Rn_SOIL, Evap, EVAP, Trap, r_a_SOIL, Resis_a, Srt]` are used in other places in the model. So, they will be empty. Is this correct?
3. In this [if block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L82-L86), check the statements. They are both the same. This cannot be correct.
4. in this [if block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L100-L106), check the statements. They are all the same. This cannot be correct.
5. In this [if block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/STEMMUS_SCOPE.m#L780-L802), variable `hN` is calculated. However, if one of those conditions doesn't happen, `hN` will be an empty variable. Later, empty `hN` is used in `h_BC` to calculate other variables, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/h_sub.m#L31C90-L31C94). This is not correct. Please check.
6. in h_BC [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/h_BC.m#L22), variable `h_SUR` is used to calculate variable `RHS`. However, `h_SUR` is not calculated somewhere else and its values are zeros. Is this correct?
7. The value of Z is hardcoded [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L35), i.e. `Z = 3421;             % altitute of the location(m).` This cannot be correct. Please check!
8. can you explain what is happening [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L264), i.e. `bx(ML, ND) = bx(MN);`
9. there are three variables `Evap` and `EVAP` and `Evapo` (this one is unused) in the codes. Is this correct?
10. there are two variables `Trap` and `trap` (this one is unused) in the codes. Is this correct?
11. variable  `Resis_a` is calculated [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L153). But it i snot used somewhere else. Is this correct? if so, it will be removed!
12. can you add a reference or explanation for [function h_Bndry_Flux](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/h_Bndry_Flux.m)

**Comment by yijianzeng** [comment]
> @yijianzeng For each function below, please add one line explanation and suggest a better name in this issue, thanks
> 
> * h_sub
This function is to solve the soil moisture balance equation with the Thomas algorithm ('hh_solve') to update the soil matric potential ('hh'), the finite difference time-stepping scheme of this soil moisture equation is derived in 'STEMMUS Technical Notes' section 4, Equation 4.32.

> * hPARM
This function calculates all the parameters related to matric coefficients (e.g., c1-c8) as in Equation 4.32 (STEMMUS Technical Notes, page 44).

> * h_MAT
This function assembles the coefficient matrices of Equation 4.32 (STEMMUS Technical Notes, page 44).

> * h_EQ
With all the coefficient matrices available (from 'h_MAT'), this function performs the finite difference of the time derivatives of the matrix equation as Equation 4.32 shows.

> * h_BC
This function determines the boundary condition for solving the soil moisture equation.

> * hh_Solve
This function uses Thomas algorithm to solve the tridiagonal matrix equations, which is in the form of Equation 4.25  (STEMMUS Technical Notes, page 41)

> * h_Bndry_Flux
This function calculates the soil water fluxes on the boundary node.

> * Evap_Cal
This function calculates evapotranspiration.

**Comment by yijianzeng** [comment]
> 1. in this [giant if block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L176-L309), there are many codes used to calculate variable `Trap(KT)`. However, at the bottom of the script, `Trap(KT)` is reset in the line [Trap(KT) = Tp_t(KT);](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L330C5-L330C13). Is this correct? if so, unused codes will be removed!

Hi Sarah, this part is by Yunfei, i agree with your observations. Yunfei please clarify. @Yunfei-Wang1993

**Comment by yijianzeng** [comment]
> 2\. `Evap_Cal` is calculated only `if NBCh == 1 `, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/h_BC.m#L37). Otherwise, all of the output of  `Evap_Cal` i.e. `[Rn_SOIL, Evap, EVAP, Trap, r_a_SOIL, Resis_a, Srt]` will be empty. `[Rn_SOIL, Evap, EVAP, Trap, r_a_SOIL, Resis_a, Srt]` are used in other places in the model. So, they will be empty. Is this correct?

This part will run when NBCH==3, and in this version of STEMMUS-SCOPE, we fix NBCH as 3. see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/%2Binit/setBoundaryCondition.m#L59).

**Comment by yijianzeng** [comment]
> 5\. In this [if block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/STEMMUS_SCOPE.m#L780-L802), variable `hN` is calculated. However, if one of those conditions doesn't happen, `hN` will be an empty variable. Later, empty `hN` is used in `h_BC` to calculate other variables, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/h_sub.m#L31C90-L31C94). This is not correct. Please check.

% hN     Specified value of matric head when a fist-type BC is used; It is indeed not used in this version of STEMMUS-SCOPE, since we are using the third-type BC (NBCH==3)

**Comment by yijianzeng** [comment]
> 6\. in h_BC [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/h_BC.m#L22), variable `h_SUR` is used to calculate variable `RHS`. However, `h_SUR` is not calculated somewhere else and its values are zeros. Is this correct?

`% h_SUR = Observed matric potential at surface;`

This is initialized[here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/STEMMUS_SCOPE.m#L156)

**Comment by yijianzeng** [comment]
> 7\. The value of Z is hardcoded [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L35), i.e. `Z = 3421;             % altitute of the location(m).` This cannot be correct. Please check!

You are right, Sarah, this is from Lianyu, who used STEMMUS to calculate Maqu site with an altitude 3421, which is used to calculate the atmospheric pressure. This variable should be generalized and renamed.

**Comment by yijianzeng** [comment]
> 8\. can you explain what is happening [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L264), i.e. `bx(ML, ND) = bx(MN);`

For every soil layer, there are two nodes. This part is about root length distribution, i cannot figure out what bx stands for though. @Yunfei-Wang1993 please clarify.

**Comment by yijianzeng** [comment]
> 9\. there are three variables `Evap` and `EVAP` and `Evapo` (this one is unused) in the codes. Is this correct?

This part is by Lianyu, and needs to be refactored to avoid confusion. (Yu et al. 2016 HESS paper)

**Comment by yijianzeng** [comment]
> 10\. there are two variables `Trap` and `trap` (this one is unused) in the codes. Is this correct?

'trap' should be removed.

**Comment by yijianzeng** [comment]
> 11\. variable  `Resis_a` is calculated [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L153). But it i snot used somewhere else. Is this correct? if so, it will be removed!

It seems Yunfei used r_a_SOIL to replace Resis_a? and then get this r_a_SOIL form initialization? @Yunfei-Wang1993  please clarify.

**Comment by yijianzeng** [comment]
> 12\. can you add a reference or explanation for [function h_Bndry_Flux](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/h_Bndry_Flux.m)

This is to calculate boundary fluxes according to Equation 4.25, following Chris Milly's approach (MIT report nr. 258, the coupled transport of water and heat in a vertical soil column under atmospheric excitation)

**Comment by SarahAlidoost** [comment]
> > 6. in h_BC [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/h_BC.m#L22), variable `h_SUR` is used to calculate variable `RHS`. However, `h_SUR` is not calculated somewhere else and its values are zeros. Is this correct?
> 
> `% h_SUR = Observed matric potential at surface;`
> 
> This is initialized[here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/STEMMUS_SCOPE.m#L156)

Right, `h_SUR` is initialized with zeroes. But the issue is that this variable is not updated/calculated anywhere else in the model. It remains zeros although it is used to derive other variables. Is this correct?

**Comment by SarahAlidoost** [comment]
> > 7. The value of Z is hardcoded [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L35), i.e. `Z = 3421;             % altitute of the location(m).` This cannot be correct. Please check!
> 
> You are right, Sarah, this is from Lianyu, who used STEMMUS to calculate Maqu site with an altitude 3421, which is used to calculate the atmospheric pressure. This variable should be generalized and renamed.

Please note that fixing `Z` might change the results of the model. I will update you about the changes.

**Comment by SarahAlidoost** [comment]
> > 8. can you explain what is happening [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L264), i.e. `bx(ML, ND) = bx(MN);`
> 
> For every soil layer, there are two nodes. This part is about root length distribution, i cannot figure out what bx stands for though. @Yunfei-Wang1993 please clarify.

The issue is that `bx` is a two-dimensional array. In this line, i.e. `bx(ML, ND) = bx(MN);` the item `(ML, ND)` is replaced by the item `(MN)` from the same variable `bx`.  Also, on the left side of this term, `bx` is a 2d array whereas on the right side, it is a 1d array. Can you explain the logic here?

**Comment by yijianzeng** [comment]
> > > 6. in h_BC [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/h_BC.m#L22), variable `h_SUR` is used to calculate variable `RHS`. However, `h_SUR` is not calculated somewhere else and its values are zeros. Is this correct?
> > 
> > 
> > `% h_SUR = Observed matric potential at surface;`
> > This is initialized[here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/STEMMUS_SCOPE.m#L156)
> 
> Right, `h_SUR` is initialized with zeroes. But the issue is that this variable is not updated/calculated anywhere else in the model. It remains zeros although it is used to derive other variables. Is this correct?

Hi Sarah, 'h_SUR' is not used to derive other variables. It just serves a placeholder to provide surface soil matric potential measurements as the first-type of boundary conditions.

**Comment by SarahAlidoost** [comment]
> > > > 6. in h_BC [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/h_BC.m#L22), variable `h_SUR` is used to calculate variable `RHS`. However, `h_SUR` is not calculated somewhere else and its values are zeros. Is this correct?
> > > 
> > > 
> > > `% h_SUR = Observed matric potential at surface;`
> > > This is initialized[here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/STEMMUS_SCOPE.m#L156)
> > 
> > 
> > Right, `h_SUR` is initialized with zeroes. But the issue is that this variable is not updated/calculated anywhere else in the model. It remains zeros although it is used to derive other variables. Is this correct?
> 
> Hi Sarah, 'h_SUR' is not used to derive other variables. 

Have you seen [these lines](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/h_BC.m#L22-L24) where 'h_SUR' is used to derive variable `RHS`. Can you elaborate on this?

**Comment by Yunfei-Wang1993** [comment]
> > 1. in this [giant if block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L176-L309), there are many codes used to calculate variable `Trap(KT)`. However, at the bottom of the script, `Trap(KT)` is reset in the line [Trap(KT) = Tp_t(KT);](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L330C5-L330C13). Is this correct? if so, unused codes will be removed!
> 
> Hi Sarah, this part is by Yunfei, i agree with your observations. Yunfei please clarify. @Yunfei-Wang1993

Hi Sarah and Yijian, you are correct, the unused codes can be removed.

**Comment by Yunfei-Wang1993** [comment]
> > 8. can you explain what is happening [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L264), i.e. `bx(ML, ND) = bx(MN);`
> 
> For every soil layer, there are two nodes. This part is about root length distribution, i cannot figure out what bx stands for though. @Yunfei-Wang1993 please clarify.

This part is referred to the code developed by Lianyu, and the 'bx(ML)' means if the root exist in the soil layer 'ML'. When the soil layer have root, the bx(ML)=1. Otherwise, bx(ML) will be 0.

**Comment by yijianzeng** [comment]
> > > 8. can you explain what is happening [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/Evap_Cal.m#L264), i.e. `bx(ML, ND) = bx(MN);`
> > 
> > 
> > For every soil layer, there are two nodes. This part is about root length distribution, i cannot figure out what bx stands for though. @Yunfei-Wang1993 please clarify.
> 
> This part is referred to the code developed by Lianyu, and the 'bx(ML)' means if the root exist in the soil layer 'ML'. When the soil layer have root, the bx(ML)=1. Otherwise, bx(ML) will be 0.

Yunfei, also check Sarah's comments [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/issues/98#issuecomment-1691214741) .
